// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVejIywRjBsr0BgcfP8LvF3REA3F8Jw8w',
    appId: '1:665559661775:web:2d5fc68f53783efe858bba',
    messagingSenderId: '665559661775',
    projectId: 'testing-cli-b2f21',
    authDomain: 'testing-cli-b2f21.firebaseapp.com',
    storageBucket: 'testing-cli-b2f21.appspot.com',
    measurementId: 'G-EP4N28ENYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXL7nQ1i5M8iegA6HNIBBDv9jx7ijbXqs',
    appId: '1:665559661775:android:588c14bbbedc5b9f858bba',
    messagingSenderId: '665559661775',
    projectId: 'testing-cli-b2f21',
    storageBucket: 'testing-cli-b2f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3AlGDgEoLxMMJgaFXoS2QK4GqdYLdl4s',
    appId: '1:665559661775:ios:45c41dc210e241dd858bba',
    messagingSenderId: '665559661775',
    projectId: 'testing-cli-b2f21',
    storageBucket: 'testing-cli-b2f21.appspot.com',
    iosBundleId: 'com.example.fireeeeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3AlGDgEoLxMMJgaFXoS2QK4GqdYLdl4s',
    appId: '1:665559661775:ios:45c41dc210e241dd858bba',
    messagingSenderId: '665559661775',
    projectId: 'testing-cli-b2f21',
    storageBucket: 'testing-cli-b2f21.appspot.com',
    iosBundleId: 'com.example.fireeeeee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVejIywRjBsr0BgcfP8LvF3REA3F8Jw8w',
    appId: '1:665559661775:web:943df841d00e7cc7858bba',
    messagingSenderId: '665559661775',
    projectId: 'testing-cli-b2f21',
    authDomain: 'testing-cli-b2f21.firebaseapp.com',
    storageBucket: 'testing-cli-b2f21.appspot.com',
    measurementId: 'G-KT8NRWSTRP',
  );
}
